### ISSUE TITLE
User creation does not allow valid email addresses

### ISSUE THREAD

**Issue by olemerdy** [kodokojo/kodokojo-ui#50]
Hi,

I tried to create a new user on [Kodo Kojo SaaS](https://my.kodokojo.io/) and I was prompted my totally valid email address (which looks like `foobar+kodojo@mymail.com`) was actually invalid.

Could you please fix the validation rules to allow theses kinds of email addresses?

Thanks a lot!

**Comment by ModuloM** [comment]
Hi,

Thanks to report this issue!
You are right, we not follow exactly the email pattern specifications and we missed valid "+" character. I'll patch the UI to fix that.
I'll update this issue as soon as it is up in production (most probably this evening).

**Comment by ModuloM** [comment]
I've push a patch, PR #51 will fix this
(will be deploy to our SaaS this evening)

**Comment by ModuloM** [comment]
Issue is fixed by https://github.com/kodokojo/kodokojo-ui/commit/e0280c49d334b249c34dab02ec3aeb4299c0b3d9, please reopen if necessary.
