### ISSUE TITLE
4-letter project name is invalid while the help claims it is accepted

### ISSUE THREAD

**Issue by olemerdy-fa** [kodokojo/kodokojo-ui#54]
When I enter a new project name of 4 characters (e.g. 'toto'), it is marked invalid while the help text claims the "name must have between 4 and 20 [...] characters".

Either the validation rule or the help text is incorrect. I would personnally rather have a 4-letter project name valid :)

See the screenshot:

![capture d ecran 2016-11-10 a 09 53 07](https://cloud.githubusercontent.com/assets/1202500/20170473/a8f435bc-a72c-11e6-9077-b7b4c549102b.png)

**Comment by ModuloM** [comment]
Oh! Indeed.
I've recently changed the regexp to exclude spaces, it apparently count as a character. 
Fix will be up in our next release on the SaaS platform (1.0.3). We will display number in the ui somewhere :)
